(in-package #:typecast/rust-ratatui)

;;;; File emission — assembles rendered code and writes to disk

(defconstant +non-type-file-count+ 7
  "Files written beyond per-type files: traits, primitives, list_editor, kv_editor, optional_field, root_form, mod.")

(defun emit-generated-files (schema sorted-types output-dir)
  "Write all generated Rust files to OUTPUT-DIR."
  (ensure-directories-exist (merge-pathnames "mod.rs" output-dir))

  ;; Shared static files
  (write-file (merge-pathnames "traits.rs" output-dir)
              (render-traits-rs))
  (write-file (merge-pathnames "primitives.rs" output-dir)
              (render-primitives-rs))
  (write-file (merge-pathnames "list_editor.rs" output-dir)
              (render-list-editor-rs))
  (write-file (merge-pathnames "kv_editor.rs" output-dir)
              (render-kv-editor-rs))
  (write-file (merge-pathnames "optional_field.rs" output-dir)
              (render-optional-field-rs))

  ;; Per-type files
  (dolist (pair sorted-types)
    (destructuring-bind (name . type-def) pair
      (let* ((filename (format nil "~A.rs" (type-name-to-filename name)))
             (filepath (merge-pathnames filename output-dir)))
        (write-file filepath (render-type-file type-def schema)))))

  ;; Root form
  (write-file (merge-pathnames "root_form.rs" output-dir)
              (render-root-form-rs schema))

  ;; mod.rs
  (write-file (merge-pathnames "mod.rs" output-dir)
              (render-mod-rs sorted-types)))

(defun render-type-file (type-def schema)
  "Render a complete per-type .rs file containing the data type and component."
  (with-output-to-string (out)
    (format out "// Generated by typecast — do not edit by hand~%")
    ;; Imports
    (format out "use serde::{Deserialize, Serialize};~%")
    (format out "#[allow(unused_imports)]~%")
    (format out "use std::collections::HashMap;~%")
    (format out "~%")
    ;; Named-ref dependency imports
    (let ((deps (type-dependencies type-def)))
      (when deps
        (dolist (dep (sort (copy-list deps) #'string<))
          (format out "use super::~A::~A;~%" (type-name-to-filename dep) dep))
        (format out "~%")))
    ;; Additional imports for components
    (when (or (object-type-p type-def) (union-type-p type-def))
      (format out "#[allow(unused_imports)]~%")
      (format out "use super::traits::FormComponent;~%")
      (format out "~%"))
    ;; Data type
    (write-string (render-data-type type-def) out)
    (format out "~%")
    ;; Default impl (if applicable)
    (let ((default-impl (render-default-impl type-def)))
      (when default-impl
        (write-string default-impl out)
        (format out "~%")))
    ;; Component
    (let ((component (render-component type-def schema)))
      (when component
        (write-string component out)))))

(defun render-mod-rs (sorted-types)
  "Render the mod.rs file with all module declarations and re-exports."
  (with-output-to-string (out)
    (format out "// Generated by typecast — do not edit by hand~%")
    (format out "~%")
    ;; Module declarations
    (format out "pub mod traits;~%")
    (format out "pub mod primitives;~%")
    (format out "pub mod list_editor;~%")
    (format out "pub mod kv_editor;~%")
    (format out "pub mod optional_field;~%")
    (format out "~%")
    (dolist (pair sorted-types)
      (let ((name (car pair)))
        (format out "pub mod ~A;~%" (type-name-to-filename name))))
    (format out "~%")
    (format out "pub mod root_form;~%")
    (format out "~%")
    ;; Re-exports
    (format out "// Re-exports~%")
    (format out "pub use traits::FormComponent;~%")
    (format out "pub use root_form::RootForm;~%")
    (format out "~%")
    (dolist (pair sorted-types)
      (let ((name (car pair)))
        (format out "pub use ~A::~A;~%" (type-name-to-filename name) name)))
    (format out "~%")
    ;; Re-export form types for objects and unions
    (dolist (pair sorted-types)
      (destructuring-bind (name . type-def) pair
        (when (or (object-type-p type-def) (union-type-p type-def))
          (format out "pub use ~A::~AForm;~%" (type-name-to-filename name) name))))))

(defun write-file (path content)
  "Write CONTENT string to PATH, creating directories as needed."
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output
                            :if-exists :supersede
                            :if-does-not-exist :create)
    (write-string content out))
  (format t "  wrote ~A~%" (enough-namestring path)))
