// Generated by typecast — do not edit by hand
use crossterm::event::{KeyCode, KeyEvent};
use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};
use tui_input::backend::crossterm::EventHandler;
use tui_input::Input;

use super::traits::{EventResult, FormComponent};

struct KvEntry<C> {
    key: Input,
    key_error: Option<String>,
    value: C,
    expanded: bool,
}

pub struct KvEditor<C: FormComponent> {
    pub label: String,
    entries: Vec<KvEntry<C>>,
}

impl<C: FormComponent> KvEditor<C>
where
    C::Model: Clone + Default,
{
    pub fn new(label: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            entries: Vec::new(),
        }
    }

    pub fn from_pairs(
        label: impl Into<String>,
        pairs: &[(String, C::Model)],
    ) -> Self {
        let entries = pairs.iter()
            .map(|(k, v)| KvEntry {
                key: Input::new(k.clone()),
                key_error: None,
                value: C::from_model(v),
                expanded: false,
            })
            .collect();
        Self {
            label: label.into(),
            entries,
        }
    }

    pub fn to_pairs(&self) -> Vec<(String, C::Model)> {
        self.entries.iter()
            .map(|e| (e.key.value().to_string(), e.value.to_model()))
            .collect()
    }

    fn entry_field_count(entry: &KvEntry<C>) -> usize {
        if entry.expanded {
            1 + entry.value.field_count() // key field + value component
        } else {
            1 // collapsed summary
        }
    }

    fn locate_entry(&self, focus_offset: usize) -> Option<(usize, usize)> {
        let mut remaining = focus_offset;
        for (i, entry) in self.entries.iter().enumerate() {
            let count = Self::entry_field_count(entry);
            if remaining < count {
                return Some((i, remaining));
            }
            remaining -= count;
        }
        None
    }

    pub fn field_count_impl(&self) -> usize {
        let entries_count: usize = self.entries.iter()
            .map(|e| Self::entry_field_count(e))
            .sum();
        entries_count + 2
    }

    pub fn handle_key_impl(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        let entries_count: usize = self.entries.iter()
            .map(|e| Self::entry_field_count(e))
            .sum();

        if focus_offset >= entries_count {
            let button_idx = focus_offset - entries_count;
            match key.code {
                KeyCode::Char(' ') | KeyCode::Enter => {
                    if button_idx == 0 {
                        self.entries.push(KvEntry {
                            key: Input::default(),
                            key_error: None,
                            value: C::from_model(&C::Model::default()),
                            expanded: true,
                        });
                    } else if !self.entries.is_empty() {
                        self.entries.pop();
                    }
                    EventResult::Consumed
                }
                _ => EventResult::Ignored,
            }
        } else if let Some((entry_idx, local_offset)) = self.locate_entry(focus_offset) {
            let entry = &mut self.entries[entry_idx];
            if !entry.expanded {
                match key.code {
                    KeyCode::Enter | KeyCode::Char(' ') => {
                        entry.expanded = true;
                        EventResult::Consumed
                    }
                    _ => EventResult::Ignored,
                }
            } else if local_offset == 0 {
                // Key field
                if key.code == KeyCode::Esc {
                    entry.expanded = false;
                    return EventResult::Consumed;
                }
                if let Some(req) = super::primitives::key_to_input_request(key) {
                    entry.key.handle(req);
                    EventResult::Consumed
                } else {
                    EventResult::Ignored
                }
            } else {
                entry.value.handle_key(local_offset - 1, key)
            }
        } else {
            EventResult::Ignored
        }
    }

    pub fn validate_impl(&mut self) -> Vec<String> {
        let mut errors = Vec::new();
        for (i, entry) in self.entries.iter_mut().enumerate() {
            entry.key_error = None;
            if entry.key.value().is_empty() {
                let msg = format!("{}[{}]: key is required", self.label, i);
                entry.key_error = Some(msg.clone());
                errors.push(msg);
            }
            let val_errors = entry.value.validate();
            for err in val_errors {
                errors.push(format!("{}[{}]: {}", self.label, i, err));
            }
        }
        errors
    }

    pub fn render_lines_impl(
        &self,
        focused_field: Option<usize>,
        show_errors: bool,
    ) -> Vec<Line<'static>> {
        let mut lines = Vec::new();
        let header_style = Style::default().fg(Color::Yellow).add_modifier(Modifier::BOLD);
        lines.push(Line::from(Span::styled(
            format!("── {} ({}) ──", self.label, self.entries.len()),
            header_style,
        )));

        let mut offset = 0usize;
        for (i, entry) in self.entries.iter().enumerate() {
            if entry.expanded {
                let key_focused = focused_field == Some(offset);
                let key_style = if key_focused {
                    Style::default().fg(Color::Black).bg(Color::Cyan)
                } else {
                    Style::default().fg(Color::White)
                };
                let key_err = if show_errors { entry.key_error.as_deref() } else { None };
                let mut key_spans: Vec<Span<'static>> = vec![
                    Span::raw(format!("  {i}. key: ")),
                    Span::styled(format!("[{}]", entry.key.value()), key_style),
                ];
                if let Some(err) = key_err {
                    key_spans.push(Span::styled(
                        format!(" ← {err}"),
                        Style::default().fg(Color::Red),
                    ));
                }
                lines.push(Line::from(key_spans));

                let val_count = entry.value.field_count();
                let val_focus = focused_field.and_then(|f| {
                    if f > offset && f <= offset + val_count { Some(f - offset - 1) } else { None }
                });
                let val_lines = entry.value.render_lines(val_focus, show_errors);
                lines.extend(val_lines.into_iter().map(|l| {
                    let mut spans = vec![Span::raw("     ")];
                    spans.extend(l.spans.into_iter());
                    Line::from(spans)
                }));

                offset += 1 + val_count;
            } else {
                let focused = focused_field == Some(offset);
                let style = if focused {
                    Style::default().fg(Color::Black).bg(Color::Cyan)
                } else {
                    Style::default().fg(Color::DarkGray)
                };
                let summary = entry.value.summary_line();
                lines.push(Line::from(vec![
                    Span::raw(format!("  {i}. ")),
                    Span::styled(
                        format!("▸ {}: {summary}", entry.key.value()),
                        style,
                    ),
                ]));
                offset += 1;
            }
        }

        let entries_total = offset;
        let add_focused = focused_field == Some(entries_total);
        let rem_focused = focused_field == Some(entries_total + 1);
        let add_style = if add_focused {
            Style::default().fg(Color::Black).bg(Color::Green)
        } else { Style::default().fg(Color::Green) };
        let rem_style = if rem_focused {
            Style::default().fg(Color::Black).bg(Color::Red)
        } else { Style::default().fg(Color::Red) };
        lines.push(Line::from(vec![
            Span::styled("  [+ Add]", add_style),
            Span::raw("  "),
            Span::styled("  [- Remove]", rem_style),
        ]));

        lines
    }
}

impl<C: FormComponent> Default for KvEditor<C>
where
    C::Model: Clone + Default,
{
    fn default() -> Self {
        Self::new("")
    }
}

impl<C: FormComponent> FormComponent for KvEditor<C>
where
    C::Model: Clone + Default,
{
    type Model = std::collections::HashMap<String, C::Model>;

    fn from_model(model: &std::collections::HashMap<String, C::Model>) -> Self {
        let pairs: Vec<(String, C::Model)> = model.iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        Self::from_pairs("", &pairs)
    }

    fn to_model(&self) -> std::collections::HashMap<String, C::Model> {
        self.to_pairs().into_iter().collect()
    }

    fn validate(&mut self) -> Vec<String> {
        self.validate_impl()
    }

    fn field_count(&self) -> usize {
        self.field_count_impl()
    }

    fn handle_key(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        self.handle_key_impl(focus_offset, key)
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        self.render_lines_impl(focused_field, show_errors)
    }

    fn summary_line(&self) -> String {
        format!("{} entries", self.to_pairs().len())
    }
}
