// Generated by typecast — do not edit by hand
use crossterm::event::{KeyCode, KeyEvent};
use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};

use super::traits::{EventResult, FormComponent};

struct ListItem<C> {
    component: C,
    expanded: bool,
}

pub struct ListEditor<C: FormComponent> {
    pub label: String,
    items: Vec<ListItem<C>>,
    min_items: usize,
    default_model: C::Model,
}

impl<C: FormComponent> ListEditor<C>
where
    C::Model: Clone + Default,
{
    pub fn new(label: impl Into<String>, min_items: usize) -> Self {
        let mut items = Vec::new();
        for _ in 0..min_items.max(1) {
            items.push(ListItem {
                component: C::from_model(&C::Model::default()),
                expanded: true,
            });
        }
        Self {
            label: label.into(),
            items,
            min_items,
            default_model: C::Model::default(),
        }
    }

    pub fn from_models(label: impl Into<String>, models: &[C::Model], min_items: usize) -> Self {
        let items = models.iter()
            .map(|m| ListItem {
                component: C::from_model(m),
                expanded: false,
            })
            .collect();
        Self {
            label: label.into(),
            items,
            min_items,
            default_model: C::Model::default(),
        }
    }

    pub fn to_models(&self) -> Vec<C::Model> {
        self.items.iter().map(|item| item.component.to_model()).collect()
    }

    fn item_field_count(item: &ListItem<C>) -> usize {
        if item.expanded {
            item.component.field_count()
        } else {
            1
        }
    }

    /// Find which item owns focus_offset and the offset within that item.
    /// Returns (item_index, local_offset) or None if offset is in buttons.
    fn locate_item(&self, focus_offset: usize) -> Option<(usize, usize)> {
        let mut remaining = focus_offset;
        for (i, item) in self.items.iter().enumerate() {
            let count = Self::item_field_count(item);
            if remaining < count {
                return Some((i, remaining));
            }
            remaining -= count;
        }
        None // offset is in the Add/Remove buttons
    }
}

impl<C: FormComponent> ListEditor<C>
where
    C::Model: Clone + Default,
{
    pub fn field_count_impl(&self) -> usize {
        let items_count: usize = self.items.iter()
            .map(|item| Self::item_field_count(item))
            .sum();
        items_count + 2 // +2 for Add and Remove buttons
    }

    pub fn handle_key_impl(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        let items_count: usize = self.items.iter()
            .map(|item| Self::item_field_count(item))
            .sum();

        if focus_offset >= items_count {
            // We're on a button
            let button_idx = focus_offset - items_count;
            match key.code {
                KeyCode::Char(' ') | KeyCode::Enter => {
                    if button_idx == 0 {
                        // Add
                        self.items.push(ListItem {
                            component: C::from_model(&self.default_model),
                            expanded: true,
                        });
                    } else if self.items.len() > self.min_items {
                        // Remove last
                        self.items.pop();
                    }
                    EventResult::Consumed
                }
                _ => EventResult::Ignored,
            }
        } else if let Some((item_idx, local_offset)) = self.locate_item(focus_offset) {
            let item = &mut self.items[item_idx];
            if !item.expanded {
                // Collapsed: Enter to expand
                match key.code {
                    KeyCode::Enter | KeyCode::Char(' ') => {
                        item.expanded = true;
                        EventResult::Consumed
                    }
                    _ => EventResult::Ignored,
                }
            } else if local_offset == 0 {
                // First field of expanded item: Esc to collapse
                if key.code == KeyCode::Esc {
                    item.expanded = false;
                    return EventResult::Consumed;
                }
                item.component.handle_key(local_offset, key)
            } else {
                item.component.handle_key(local_offset, key)
            }
        } else {
            EventResult::Ignored
        }
    }

    pub fn validate_impl(&mut self) -> Vec<String> {
        let mut errors = Vec::new();
        for (i, item) in self.items.iter_mut().enumerate() {
            let item_errors = item.component.validate();
            for err in item_errors {
                errors.push(format!("{}[{}]: {}", self.label, i, err));
            }
        }
        errors
    }

    pub fn render_lines_impl(
        &self,
        focused_field: Option<usize>,
        show_errors: bool,
    ) -> Vec<Line<'static>> {
        let mut lines = Vec::new();
        let header_style = Style::default().fg(Color::Yellow).add_modifier(Modifier::BOLD);
        lines.push(Line::from(Span::styled(
            format!("── {} ({}) ──", self.label, self.items.len()),
            header_style,
        )));

        let mut offset = 0usize;
        for (i, item) in self.items.iter().enumerate() {
            if item.expanded {
                let count = item.component.field_count();
                let local_focus = focused_field.and_then(|f| {
                    if f >= offset && f < offset + count { Some(f - offset) } else { None }
                });
                let item_lines = item.component.render_lines(local_focus, show_errors);
                // Add index prefix to first line
                if let Some(first) = item_lines.first() {
                    let mut spans = vec![Span::raw(format!("  {i}. "))];
                    spans.extend(first.spans.iter().cloned());
                    lines.push(Line::from(spans));
                    lines.extend(item_lines.into_iter().skip(1).map(|l| {
                        let mut spans = vec![Span::raw("     ")];
                        spans.extend(l.spans.into_iter());
                        Line::from(spans)
                    }));
                }
                offset += count;
            } else {
                let focused = focused_field == Some(offset);
                let style = if focused {
                    Style::default().fg(Color::Black).bg(Color::Cyan)
                } else {
                    Style::default().fg(Color::DarkGray)
                };
                let summary = item.component.summary_line();
                lines.push(Line::from(vec![
                    Span::raw(format!("  {i}. ")),
                    Span::styled(format!("▸ {summary}"), style),
                    Span::styled(" (Enter to expand)", Style::default().fg(Color::DarkGray)),
                ]));
                offset += 1;
            }
        }

        // Add / Remove buttons
        let items_total = offset;
        let add_focused = focused_field == Some(items_total);
        let rem_focused = focused_field == Some(items_total + 1);

        let add_style = if add_focused {
            Style::default().fg(Color::Black).bg(Color::Green)
        } else {
            Style::default().fg(Color::Green)
        };
        let rem_style = if rem_focused {
            Style::default().fg(Color::Black).bg(Color::Red)
        } else {
            Style::default().fg(Color::Red)
        };

        lines.push(Line::from(vec![
            Span::styled("  [+ Add]", add_style),
            Span::raw("  "),
            Span::styled("  [- Remove]", rem_style),
        ]));

        lines
    }

    pub fn summary_line_impl(&self) -> String {
        format!("{} items", self.items.len())
    }
}

impl<C: FormComponent> Default for ListEditor<C>
where
    C::Model: Clone + Default,
{
    fn default() -> Self {
        Self {
            label: String::new(),
            items: Vec::new(),
            min_items: 0,
            default_model: C::Model::default(),
        }
    }
}

impl<C: FormComponent> FormComponent for ListEditor<C>
where
    C::Model: Clone + Default,
{
    type Model = Vec<C::Model>;

    fn from_model(model: &Vec<C::Model>) -> Self {
        Self::from_models("", model, 0)
    }

    fn to_model(&self) -> Vec<C::Model> {
        self.to_models()
    }

    fn validate(&mut self) -> Vec<String> {
        self.validate_impl()
    }

    fn field_count(&self) -> usize {
        self.field_count_impl()
    }

    fn handle_key(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        self.handle_key_impl(focus_offset, key)
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        self.render_lines_impl(focused_field, show_errors)
    }

    fn summary_line(&self) -> String {
        self.summary_line_impl()
    }
}
