// Generated by typecast — do not edit by hand
use crossterm::event::{KeyCode, KeyEvent};
use ratatui::style::{Color, Style};
use ratatui::text::{Line, Span};

use super::traits::{EventResult, FormComponent};

pub struct OptionalField<C: FormComponent> {
    pub label: String,
    pub enabled: bool,
    pub inner: C,
}

impl<C: FormComponent> OptionalField<C>
where
    C::Model: Default,
{
    pub fn new(label: impl Into<String>, inner: C) -> Self {
        Self {
            label: label.into(),
            enabled: false,
            inner,
        }
    }

    pub fn new_enabled(label: impl Into<String>, inner: C) -> Self {
        Self {
            label: label.into(),
            enabled: true,
            inner,
        }
    }

    pub fn from_option(label: impl Into<String>, model: &Option<C::Model>) -> Self {
        match model {
            Some(m) => Self::new_enabled(label, C::from_model(m)),
            None => Self::new(label, C::from_model(&C::Model::default())),
        }
    }

    pub fn to_option(&self) -> Option<C::Model> {
        if self.enabled {
            Some(self.inner.to_model())
        } else {
            None
        }
    }
}

impl<C: FormComponent> OptionalField<C>
where
    C::Model: Default,
{
    pub fn field_count_impl(&self) -> usize {
        if self.enabled {
            1 + self.inner.field_count()
        } else {
            1
        }
    }

    pub fn handle_key_impl(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        if focus_offset == 0 {
            match key.code {
                KeyCode::Char(' ') | KeyCode::Enter => {
                    self.enabled = !self.enabled;
                    EventResult::Consumed
                }
                _ => EventResult::Ignored,
            }
        } else if self.enabled {
            self.inner.handle_key(focus_offset - 1, key)
        } else {
            EventResult::Ignored
        }
    }

    pub fn validate_impl(&mut self) -> Vec<String> {
        if self.enabled {
            self.inner.validate()
        } else {
            vec![]
        }
    }

    pub fn render_lines_impl(
        &self,
        focused_field: Option<usize>,
        show_errors: bool,
    ) -> Vec<Line<'static>> {
        let mut lines = Vec::new();
        let toggle_focused = focused_field == Some(0);
        let check = if self.enabled { "x" } else { " " };
        let style = if toggle_focused {
            Style::default().fg(Color::Black).bg(Color::Cyan)
        } else {
            Style::default().fg(Color::White)
        };
        lines.push(Line::from(vec![
            Span::raw(format!("{}: ", self.label)),
            Span::styled(format!("[{check}] enabled"), style),
        ]));

        if self.enabled {
            let inner_focus = focused_field.and_then(|f| {
                if f > 0 { Some(f - 1) } else { None }
            });
            let inner_lines = self.inner.render_lines(inner_focus, show_errors);
            lines.extend(inner_lines.into_iter().map(|l| {
                let mut spans = vec![Span::raw("  ")];
                spans.extend(l.spans.into_iter());
                Line::from(spans)
            }));
        }

        lines
    }
}

impl<C: FormComponent + Default> Default for OptionalField<C>
where
    C::Model: Default,
{
    fn default() -> Self {
        Self {
            label: String::new(),
            enabled: false,
            inner: C::default(),
        }
    }
}
