// Generated by typecast — do not edit by hand
use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use ratatui::style::{Color, Style};
use ratatui::text::{Line, Span};
use tui_input::backend::crossterm::EventHandler;
use tui_input::Input;

use super::traits::{EventResult, FormComponent};

// ─── Helpers ──────────────────────────────────────────────────────────

fn styled_field_line(label: &str, value: &str, focused: bool, error: Option<&str>) -> Line<'static> {
    let input_style = if focused {
        Style::default().fg(Color::Black).bg(Color::Cyan)
    } else {
        Style::default().fg(Color::White)
    };
    let mut spans: Vec<Span<'static>> = vec![
        Span::raw(format!("{label}: ")),
        Span::styled(format!("[{value}]"), input_style),
    ];
    if let Some(err) = error {
        spans.push(Span::styled(
            format!(" ← {err}"),
            Style::default().fg(Color::Red),
        ));
    }
    Line::from(spans)
}

pub fn key_to_input_request(key: KeyEvent) -> Option<tui_input::InputRequest> {
    use tui_input::InputRequest::*;
    match key.code {
        KeyCode::Char(c) => Some(InsertChar(c)),
        KeyCode::Backspace => Some(DeletePrevChar),
        KeyCode::Delete => Some(DeleteNextChar),
        KeyCode::Left => {
            if key.modifiers.contains(KeyModifiers::CONTROL) {
                Some(GoToPrevWord)
            } else {
                Some(GoToPrevChar)
            }
        }
        KeyCode::Right => {
            if key.modifiers.contains(KeyModifiers::CONTROL) {
                Some(GoToNextWord)
            } else {
                Some(GoToNextChar)
            }
        }
        KeyCode::Home => Some(GoToStart),
        KeyCode::End => Some(GoToEnd),
        _ => None,
    }
}

// ─── TextInput ────────────────────────────────────────────────────────

pub struct TextInput {
    pub label: String,
    pub input: Input,
    pub error: Option<String>,
    pub required: bool,
    pub placeholder: Option<String>,
    pub help: Option<String>,
}

impl TextInput {
    pub fn new(label: impl Into<String>, required: bool) -> Self {
        Self {
            label: label.into(),
            input: Input::default(),
            error: None,
            required,
            placeholder: None,
            help: None,
        }
    }

    pub fn with_value(mut self, value: &str) -> Self {
        self.input = Input::new(value.to_string());
        self
    }

    pub fn with_placeholder(mut self, p: impl Into<String>) -> Self {
        self.placeholder = Some(p.into());
        self
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }

    pub fn value(&self) -> &str {
        self.input.value()
    }
}

impl FormComponent for TextInput {
    type Model = String;

    fn from_model(model: &String) -> Self {
        Self::new("", true).with_value(model)
    }

    fn to_model(&self) -> String {
        self.input.value().to_string()
    }

    fn validate(&mut self) -> Vec<String> {
        self.error = None;
        if self.required && self.input.value().is_empty() {
            let msg = format!("{} is required", self.label);
            self.error = Some(msg.clone());
            vec![msg]
        } else {
            vec![]
        }
    }

    fn field_count(&self) -> usize { 1 }

    fn handle_key(&mut self, _focus_offset: usize, key: KeyEvent) -> EventResult {
        if let Some(req) = key_to_input_request(key) {
            self.input.handle(req);
            EventResult::Consumed
        } else {
            EventResult::Ignored
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        let focused = focused_field == Some(0);
        let err = if show_errors { self.error.as_deref() } else { None };
        let display = if self.input.value().is_empty() {
            self.placeholder.as_deref().unwrap_or("")
        } else {
            self.input.value()
        };
        vec![styled_field_line(&self.label, display, focused, err)]
    }

    fn summary_line(&self) -> String {
        self.input.value().to_string()
    }
}

// ─── NumericInput ─────────────────────────────────────────────────────

pub struct NumericInput {
    pub label: String,
    pub input: Input,
    pub error: Option<String>,
    pub required: bool,
    pub min: Option<i64>,
    pub max: Option<i64>,
    pub placeholder: Option<String>,
    pub help: Option<String>,
}

impl NumericInput {
    pub fn new(label: impl Into<String>, required: bool) -> Self {
        Self {
            label: label.into(),
            input: Input::default(),
            error: None,
            required,
            min: None,
            max: None,
            placeholder: None,
            help: None,
        }
    }

    pub fn with_value(mut self, v: i64) -> Self {
        self.input = Input::new(v.to_string());
        self
    }

    pub fn with_min(mut self, m: i64) -> Self { self.min = Some(m); self }
    pub fn with_max(mut self, m: i64) -> Self { self.max = Some(m); self }

    pub fn with_placeholder(mut self, p: impl Into<String>) -> Self {
        self.placeholder = Some(p.into());
        self
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }

    pub fn parse_value(&self) -> Option<i64> {
        self.input.value().parse().ok()
    }

    fn numeric_req(key: KeyEvent) -> Option<tui_input::InputRequest> {
        if let KeyCode::Char(c) = key.code {
            if !c.is_ascii_digit() && c != '-' {
                return None;
            }
        }
        key_to_input_request(key)
    }
}

impl FormComponent for NumericInput {
    type Model = i64;

    fn from_model(model: &i64) -> Self {
        Self::new("", true).with_value(*model)
    }

    fn to_model(&self) -> i64 {
        self.parse_value().unwrap_or(0)
    }

    fn validate(&mut self) -> Vec<String> {
        self.error = None;
        let val = self.input.value();
        if val.is_empty() {
            if self.required {
                let msg = format!("{} is required", self.label);
                self.error = Some(msg.clone());
                return vec![msg];
            }
            return vec![];
        }
        match val.parse::<i64>() {
            Err(_) => {
                let msg = format!("{}: not a valid integer", self.label);
                self.error = Some(msg.clone());
                vec![msg]
            }
            Ok(n) => {
                if let Some(min) = self.min {
                    if n < min {
                        let msg = format!("{}: must be >= {}", self.label, min);
                        self.error = Some(msg.clone());
                        return vec![msg];
                    }
                }
                if let Some(max) = self.max {
                    if n > max {
                        let msg = format!("{}: must be <= {}", self.label, max);
                        self.error = Some(msg.clone());
                        return vec![msg];
                    }
                }
                vec![]
            }
        }
    }

    fn field_count(&self) -> usize { 1 }

    fn handle_key(&mut self, _focus_offset: usize, key: KeyEvent) -> EventResult {
        if let Some(req) = Self::numeric_req(key) {
            self.input.handle(req);
            EventResult::Consumed
        } else {
            EventResult::Ignored
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        let focused = focused_field == Some(0);
        let err = if show_errors { self.error.as_deref() } else { None };
        let display = if self.input.value().is_empty() {
            self.placeholder.as_deref().unwrap_or("")
        } else {
            self.input.value()
        };
        vec![styled_field_line(&self.label, display, focused, err)]
    }

    fn summary_line(&self) -> String {
        self.input.value().to_string()
    }
}

// ─── FloatInput ───────────────────────────────────────────────────────

pub struct FloatInput {
    pub label: String,
    pub input: Input,
    pub error: Option<String>,
    pub required: bool,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub min_exclusive: Option<f64>,
    pub placeholder: Option<String>,
    pub help: Option<String>,
}

impl FloatInput {
    pub fn new(label: impl Into<String>, required: bool) -> Self {
        Self {
            label: label.into(),
            input: Input::default(),
            error: None,
            required,
            min: None,
            max: None,
            min_exclusive: None,
            placeholder: None,
            help: None,
        }
    }

    pub fn with_value(mut self, v: f64) -> Self {
        self.input = Input::new(v.to_string());
        self
    }

    pub fn with_min(mut self, m: f64) -> Self { self.min = Some(m); self }
    pub fn with_max(mut self, m: f64) -> Self { self.max = Some(m); self }
    pub fn with_min_exclusive(mut self, m: f64) -> Self { self.min_exclusive = Some(m); self }

    pub fn with_placeholder(mut self, p: impl Into<String>) -> Self {
        self.placeholder = Some(p.into());
        self
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }

    pub fn parse_value(&self) -> Option<f64> {
        self.input.value().parse().ok()
    }

    fn float_req(key: KeyEvent) -> Option<tui_input::InputRequest> {
        if let KeyCode::Char(c) = key.code {
            if !c.is_ascii_digit() && c != '.' && c != '-' {
                return None;
            }
        }
        key_to_input_request(key)
    }
}

impl FormComponent for FloatInput {
    type Model = f64;

    fn from_model(model: &f64) -> Self {
        Self::new("", true).with_value(*model)
    }

    fn to_model(&self) -> f64 {
        self.parse_value().unwrap_or(0.0)
    }

    fn validate(&mut self) -> Vec<String> {
        self.error = None;
        let val = self.input.value();
        if val.is_empty() {
            if self.required {
                let msg = format!("{} is required", self.label);
                self.error = Some(msg.clone());
                return vec![msg];
            }
            return vec![];
        }
        match val.parse::<f64>() {
            Err(_) => {
                let msg = format!("{}: not a valid number", self.label);
                self.error = Some(msg.clone());
                vec![msg]
            }
            Ok(n) => {
                if let Some(min) = self.min {
                    if n < min {
                        let msg = format!("{}: must be >= {}", self.label, min);
                        self.error = Some(msg.clone());
                        return vec![msg];
                    }
                }
                if let Some(me) = self.min_exclusive {
                    if n <= me {
                        let msg = format!("{}: must be > {}", self.label, me);
                        self.error = Some(msg.clone());
                        return vec![msg];
                    }
                }
                if let Some(max) = self.max {
                    if n > max {
                        let msg = format!("{}: must be <= {}", self.label, max);
                        self.error = Some(msg.clone());
                        return vec![msg];
                    }
                }
                vec![]
            }
        }
    }

    fn field_count(&self) -> usize { 1 }

    fn handle_key(&mut self, _focus_offset: usize, key: KeyEvent) -> EventResult {
        if let Some(req) = Self::float_req(key) {
            self.input.handle(req);
            EventResult::Consumed
        } else {
            EventResult::Ignored
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        let focused = focused_field == Some(0);
        let err = if show_errors { self.error.as_deref() } else { None };
        let display = if self.input.value().is_empty() {
            self.placeholder.as_deref().unwrap_or("")
        } else {
            self.input.value()
        };
        vec![styled_field_line(&self.label, display, focused, err)]
    }

    fn summary_line(&self) -> String {
        self.input.value().to_string()
    }
}

// ─── Toggle ───────────────────────────────────────────────────────────

pub struct Toggle {
    pub label: String,
    pub value: bool,
    pub help: Option<String>,
}

impl Toggle {
    pub fn new(label: impl Into<String>, default: bool) -> Self {
        Self {
            label: label.into(),
            value: default,
            help: None,
        }
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }
}

impl FormComponent for Toggle {
    type Model = bool;

    fn from_model(model: &bool) -> Self {
        Self::new("", *model)
    }

    fn to_model(&self) -> bool {
        self.value
    }

    fn validate(&mut self) -> Vec<String> { vec![] }

    fn field_count(&self) -> usize { 1 }

    fn handle_key(&mut self, _focus_offset: usize, key: KeyEvent) -> EventResult {
        match key.code {
            KeyCode::Char(' ') | KeyCode::Enter => {
                self.value = !self.value;
                EventResult::Consumed
            }
            _ => EventResult::Ignored,
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, _show_errors: bool) -> Vec<Line<'static>> {
        let focused = focused_field == Some(0);
        let check = if self.value { "x" } else { " " };
        let style = if focused {
            Style::default().fg(Color::Black).bg(Color::Cyan)
        } else {
            Style::default().fg(Color::White)
        };
        vec![Line::from(vec![
            Span::raw(format!("{}: ", self.label)),
            Span::styled(format!("[{check}]"), style),
        ])]
    }

    fn summary_line(&self) -> String {
        if self.value { "true".into() } else { "false".into() }
    }
}

// ─── SelectList ───────────────────────────────────────────────────────

pub struct SelectList<T: Clone + PartialEq> {
    pub label: String,
    pub options: Vec<(T, String)>,  // (value, display_label)
    pub selected: usize,
    pub help: Option<String>,
}

impl<T: Clone + PartialEq> SelectList<T> {
    pub fn new(label: impl Into<String>, options: Vec<(T, String)>, default: &T) -> Self {
        let selected = options.iter()
            .position(|(v, _)| v == default)
            .unwrap_or(0);
        Self {
            label: label.into(),
            options,
            selected,
            help: None,
        }
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }

    pub fn current_value(&self) -> &T {
        &self.options[self.selected].0
    }

    pub fn current_label(&self) -> &str {
        &self.options[self.selected].1
    }

    fn cycle_next(&mut self) {
        self.selected = (self.selected + 1) % self.options.len();
    }

    fn cycle_prev(&mut self) {
        self.selected = (self.selected + self.options.len() - 1) % self.options.len();
    }
}

impl<T: Clone + PartialEq + Default> FormComponent for SelectList<T> {
    type Model = T;

    fn from_model(model: &T) -> Self {
        Self {
            label: String::new(),
            options: vec![(model.clone(), String::new())],
            selected: 0,
            help: None,
        }
    }

    fn to_model(&self) -> T {
        self.current_value().clone()
    }

    fn validate(&mut self) -> Vec<String> { vec![] }

    fn field_count(&self) -> usize { 1 }

    fn handle_key(&mut self, _focus_offset: usize, key: KeyEvent) -> EventResult {
        match key.code {
            KeyCode::Right | KeyCode::Char(' ') | KeyCode::Enter => {
                self.cycle_next();
                EventResult::Consumed
            }
            KeyCode::Left => {
                self.cycle_prev();
                EventResult::Consumed
            }
            _ => EventResult::Ignored,
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, _show_errors: bool) -> Vec<Line<'static>> {
        let focused = focused_field == Some(0);
        let style = if focused {
            Style::default().fg(Color::Black).bg(Color::Cyan)
        } else {
            Style::default().fg(Color::White)
        };
        vec![Line::from(vec![
            Span::raw(format!("{}: ", self.label)),
            Span::styled(format!("[ < {} > ]", self.current_label()), style),
        ])]
    }

    fn summary_line(&self) -> String {
        self.current_label().to_string()
    }
}

// ─── JsonValueEditor ──────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JsonValueType {
    String,
    Number,
    Boolean,
    Null,
    RawJson,
}

impl JsonValueType {
    pub fn label(&self) -> &'static str {
        match self {
            Self::String => "String",
            Self::Number => "Number",
            Self::Boolean => "Boolean",
            Self::Null => "Null",
            Self::RawJson => "Raw JSON",
        }
    }

    pub fn all() -> Vec<(Self, String)> {
        vec![
            (Self::String, "String".into()),
            (Self::Number, "Number".into()),
            (Self::Boolean, "Boolean".into()),
            (Self::Null, "Null".into()),
            (Self::RawJson, "Raw JSON".into()),
        ]
    }

    fn cycle_next(&self) -> Self {
        match self {
            Self::String => Self::Number,
            Self::Number => Self::Boolean,
            Self::Boolean => Self::Null,
            Self::Null => Self::RawJson,
            Self::RawJson => Self::String,
        }
    }

    fn cycle_prev(&self) -> Self {
        match self {
            Self::String => Self::RawJson,
            Self::Number => Self::String,
            Self::Boolean => Self::Number,
            Self::Null => Self::Boolean,
            Self::RawJson => Self::Null,
        }
    }
}

pub struct JsonValueEditor {
    pub label: String,
    pub value_type: JsonValueType,
    pub string_input: Input,
    pub number_input: Input,
    pub bool_value: bool,
    pub raw_input: Input,
    pub error: Option<String>,
    pub help: Option<String>,
}

impl JsonValueEditor {
    pub fn new(label: impl Into<String>) -> Self {
        Self {
            label: label.into(),
            value_type: JsonValueType::Null,
            string_input: Input::default(),
            number_input: Input::default(),
            bool_value: false,
            raw_input: Input::default(),
            error: None,
            help: None,
        }
    }

    pub fn with_help(mut self, h: impl Into<String>) -> Self {
        self.help = Some(h.into());
        self
    }

    fn sub_field_count(&self) -> usize {
        match self.value_type {
            JsonValueType::String | JsonValueType::Number |
            JsonValueType::Boolean | JsonValueType::RawJson => 1,
            JsonValueType::Null => 0,
        }
    }
}

impl FormComponent for JsonValueEditor {
    type Model = serde_json::Value;

    fn from_model(model: &serde_json::Value) -> Self {
        let mut editor = Self::new("");
        match model {
            serde_json::Value::String(s) => {
                editor.value_type = JsonValueType::String;
                editor.string_input = Input::new(s.clone());
            }
            serde_json::Value::Number(n) => {
                editor.value_type = JsonValueType::Number;
                editor.number_input = Input::new(n.to_string());
            }
            serde_json::Value::Bool(b) => {
                editor.value_type = JsonValueType::Boolean;
                editor.bool_value = *b;
            }
            serde_json::Value::Null => {
                editor.value_type = JsonValueType::Null;
            }
            other => {
                editor.value_type = JsonValueType::RawJson;
                editor.raw_input = Input::new(serde_json::to_string_pretty(other).unwrap_or_default());
            }
        }
        editor
    }

    fn to_model(&self) -> serde_json::Value {
        match self.value_type {
            JsonValueType::String => serde_json::Value::String(self.string_input.value().to_string()),
            JsonValueType::Number => {
                self.number_input.value().parse::<f64>()
                    .map(|n| serde_json::json!(n))
                    .unwrap_or(serde_json::Value::Null)
            }
            JsonValueType::Boolean => serde_json::Value::Bool(self.bool_value),
            JsonValueType::Null => serde_json::Value::Null,
            JsonValueType::RawJson => {
                serde_json::from_str(self.raw_input.value())
                    .unwrap_or(serde_json::Value::Null)
            }
        }
    }

    fn validate(&mut self) -> Vec<String> {
        self.error = None;
        match self.value_type {
            JsonValueType::Number => {
                if !self.number_input.value().is_empty()
                    && self.number_input.value().parse::<f64>().is_err()
                {
                    let msg = format!("{}: not a valid number", self.label);
                    self.error = Some(msg.clone());
                    return vec![msg];
                }
            }
            JsonValueType::RawJson => {
                if !self.raw_input.value().is_empty()
                    && serde_json::from_str::<serde_json::Value>(self.raw_input.value()).is_err()
                {
                    let msg = format!("{}: not valid JSON", self.label);
                    self.error = Some(msg.clone());
                    return vec![msg];
                }
            }
            _ => {}
        }
        vec![]
    }

    fn field_count(&self) -> usize {
        1 + self.sub_field_count()
    }

    fn handle_key(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult {
        if focus_offset == 0 {
            // Type selector
            match key.code {
                KeyCode::Right | KeyCode::Char(' ') | KeyCode::Enter => {
                    self.value_type = self.value_type.cycle_next();
                    EventResult::Consumed
                }
                KeyCode::Left => {
                    self.value_type = self.value_type.cycle_prev();
                    EventResult::Consumed
                }
                _ => EventResult::Ignored,
            }
        } else {
            // Sub-field
            match self.value_type {
                JsonValueType::String => {
                    if let Some(req) = key_to_input_request(key) {
                        self.string_input.handle(req);
                        EventResult::Consumed
                    } else {
                        EventResult::Ignored
                    }
                }
                JsonValueType::Number => {
                    if let KeyCode::Char(c) = key.code {
                        if !c.is_ascii_digit() && c != '.' && c != '-' {
                            return EventResult::Ignored;
                        }
                    }
                    if let Some(req) = key_to_input_request(key) {
                        self.number_input.handle(req);
                        EventResult::Consumed
                    } else {
                        EventResult::Ignored
                    }
                }
                JsonValueType::Boolean => {
                    match key.code {
                        KeyCode::Char(' ') | KeyCode::Enter => {
                            self.bool_value = !self.bool_value;
                            EventResult::Consumed
                        }
                        _ => EventResult::Ignored,
                    }
                }
                JsonValueType::RawJson => {
                    if let Some(req) = key_to_input_request(key) {
                        self.raw_input.handle(req);
                        EventResult::Consumed
                    } else {
                        EventResult::Ignored
                    }
                }
                JsonValueType::Null => EventResult::Ignored,
            }
        }
    }

    fn render_lines(&self, focused_field: Option<usize>, show_errors: bool) -> Vec<Line<'static>> {
        let mut lines = Vec::new();
        // Type selector line
        let type_focused = focused_field == Some(0);
        let type_style = if type_focused {
            Style::default().fg(Color::Black).bg(Color::Cyan)
        } else {
            Style::default().fg(Color::White)
        };
        lines.push(Line::from(vec![
            Span::raw(format!("{} type: ", self.label)),
            Span::styled(format!("[ < {} > ]", self.value_type.label()), type_style),
        ]));

        let sub_focused = focused_field.and_then(|f| if f > 0 { Some(0) } else { None });
        let err = if show_errors { self.error.as_deref() } else { None };

        match self.value_type {
            JsonValueType::String => {
                lines.push(styled_field_line("  value", self.string_input.value(), sub_focused == Some(0), err));
            }
            JsonValueType::Number => {
                lines.push(styled_field_line("  value", self.number_input.value(), sub_focused == Some(0), err));
            }
            JsonValueType::Boolean => {
                let check = if self.bool_value { "x" } else { " " };
                let style = if sub_focused == Some(0) {
                    Style::default().fg(Color::Black).bg(Color::Cyan)
                } else {
                    Style::default().fg(Color::White)
                };
                lines.push(Line::from(vec![
                    Span::raw("  value: "),
                    Span::styled(format!("[{check}]"), style),
                ]));
            }
            JsonValueType::RawJson => {
                lines.push(styled_field_line("  JSON", self.raw_input.value(), sub_focused == Some(0), err));
            }
            JsonValueType::Null => {}
        }

        lines
    }

    fn summary_line(&self) -> String {
        match self.value_type {
            JsonValueType::String => format!("\"{}\"" , self.string_input.value()),
            JsonValueType::Number => self.number_input.value().to_string(),
            JsonValueType::Boolean => if self.bool_value { "true".into() } else { "false".into() },
            JsonValueType::Null => "null".into(),
            JsonValueType::RawJson => {
                let v = self.raw_input.value();
                if v.len() > 30 { format!("{}...", &v[..27]) } else { v.to_string() }
            }
        }
    }
}

// ─── Default impls ────────────────────────────────────────────────────

impl Default for TextInput {
    fn default() -> Self { Self::new("", false) }
}

impl Default for NumericInput {
    fn default() -> Self { Self::new("", false) }
}

impl Default for FloatInput {
    fn default() -> Self { Self::new("", false) }
}

impl Default for Toggle {
    fn default() -> Self { Self::new("", false) }
}

impl<T: Clone + PartialEq + Default> Default for SelectList<T> {
    fn default() -> Self {
        let val = T::default();
        Self {
            label: String::new(),
            options: vec![(val, String::new())],
            selected: 0,
            help: None,
        }
    }
}

impl Default for JsonValueEditor {
    fn default() -> Self { Self::new("") }
}
