// Generated by typecast — do not edit by hand
use crossterm::event::KeyEvent;
use ratatui::text::Line;

/// Outcome of handling a key event in a form component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventResult {
    /// Event was consumed by this component.
    Consumed,
    /// Event was not handled; parent should try.
    Ignored,
}

/// Every editable schema type implements this trait.
pub trait FormComponent {
    /// The data-model type this component edits.
    type Model;

    /// Create a component pre-populated from a model value.
    fn from_model(model: &Self::Model) -> Self;

    /// Extract the current edited value.
    fn to_model(&self) -> Self::Model;

    /// Validate the current state.  Returns a list of error strings.
    /// Empty vec means valid.
    fn validate(&mut self) -> Vec<String>;

    /// Total number of focusable leaf fields in this component.
    fn field_count(&self) -> usize;

    /// Handle a key event when the `focus_offset`-th field of this
    /// component is focused.
    fn handle_key(&mut self, focus_offset: usize, key: KeyEvent) -> EventResult;

    /// Render this component's fields as `Line`s.
    /// `focused_field` is the focused index relative to this component,
    /// or `None` if focus is outside.
    fn render_lines(
        &self,
        focused_field: Option<usize>,
        show_errors: bool,
    ) -> Vec<Line<'static>>;

    /// One-line summary for collapsed list display.
    fn summary_line(&self) -> String;
}
